name: map_web
description: "Costa Blanca Insider Guide by Flamencos.eu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: false
  image_path: "lib/images/icon/flamencos.png"
  adaptive_icon_foreground: "lib/images/icon/original.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: lib/images/icon/original.png
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - lib/images/icon/original.png
